import type {
  Invoice,
  Investment,
  Farmer,
  GroceryStore,
  Investor,
  PlatformStats,
} from "./types";

// ─── Farmers ────────────────────────────────────────────────────────────────

export const FARMERS: Farmer[] = [
  {
    id: "f1",
    name: "Sunrise Valley Farm",
    location: "Salinas, CA",
    totalInvoiced: 148000,
    totalFunded: 131000,
    invoiceCount: 14,
  },
  {
    id: "f2",
    name: "Green Ridge Organics",
    location: "Fresno, CA",
    totalInvoiced: 92000,
    totalFunded: 88000,
    invoiceCount: 9,
  },
  {
    id: "f3",
    name: "Blue Sky Produce",
    location: "Stockton, CA",
    totalInvoiced: 57000,
    totalFunded: 52000,
    invoiceCount: 6,
  },
];

// ─── Grocery Stores ──────────────────────────────────────────────────────────

export const GROCERY_STORES: GroceryStore[] = [
  {
    id: "s1",
    name: "Fresh Market Co.",
    chain: "Fresh Market",
    location: "San Francisco, CA",
    pendingConfirmations: 3,
    totalOwed: 47500,
  },
  {
    id: "s2",
    name: "Valley Grocers",
    location: "Oakland, CA",
    pendingConfirmations: 1,
    totalOwed: 18000,
  },
  {
    id: "s3",
    name: "NatureMart",
    chain: "NatureMart",
    location: "San Jose, CA",
    pendingConfirmations: 2,
    totalOwed: 29750,
  },
  {
    id: "s4",
    name: "Harvest Table",
    location: "Berkeley, CA",
    pendingConfirmations: 0,
    totalOwed: 11200,
  },
];

// ─── Invoices ────────────────────────────────────────────────────────────────

export const INVOICES: Invoice[] = [
  {
    id: "inv1",
    invoiceNumber: "INV-2025-0041",
    farmerId: "f1",
    farmerName: "Sunrise Valley Farm",
    storeId: "s1",
    storeName: "Fresh Market Co.",
    amount: 12500,
    issueDate: "2026-03-01",
    dueDate: "2026-04-30",
    fundedDate: "2026-03-05",
    status: "funded",
    goods: "Organic Strawberries (1,200 lbs)",
    yieldRate: 8.0,
    platformFee: 375,
    fundedPercent: 100,
    totalInvestors: 7,
  },
  {
    id: "inv2",
    invoiceNumber: "INV-2025-0042",
    farmerId: "f1",
    farmerName: "Sunrise Valley Farm",
    storeId: "s3",
    storeName: "NatureMart",
    amount: 8750,
    issueDate: "2026-03-08",
    dueDate: "2026-05-07",
    fundedDate: "2026-03-11",
    status: "funded",
    goods: "Mixed Salad Greens (800 lbs)",
    yieldRate: 8.0,
    platformFee: 262,
    fundedPercent: 78,
    totalInvestors: 4,
  },
  {
    id: "inv3",
    invoiceNumber: "INV-2025-0043",
    farmerId: "f2",
    farmerName: "Green Ridge Organics",
    storeId: "s1",
    storeName: "Fresh Market Co.",
    amount: 15200,
    issueDate: "2026-03-12",
    dueDate: "2026-05-11",
    status: "confirmed",
    goods: "Organic Tomatoes (2,400 lbs)",
    yieldRate: 8.0,
    platformFee: 456,
    fundedPercent: 42,
    totalInvestors: 3,
  },
  {
    id: "inv4",
    invoiceNumber: "INV-2025-0044",
    farmerId: "f3",
    farmerName: "Blue Sky Produce",
    storeId: "s2",
    storeName: "Valley Grocers",
    amount: 6800,
    issueDate: "2026-03-15",
    dueDate: "2026-05-14",
    status: "confirmed",
    goods: "Sweet Corn (3,000 ears)",
    yieldRate: 8.5,
    platformFee: 204,
    fundedPercent: 15,
    totalInvestors: 1,
  },
  {
    id: "inv5",
    invoiceNumber: "INV-2025-0045",
    farmerId: "f1",
    farmerName: "Sunrise Valley Farm",
    storeId: "s4",
    storeName: "Harvest Table",
    amount: 4200,
    issueDate: "2026-03-20",
    dueDate: "2026-05-19",
    status: "submitted",
    goods: "Heirloom Tomatoes (600 lbs)",
    yieldRate: 8.0,
    platformFee: 126,
    fundedPercent: 0,
    totalInvestors: 0,
  },
  {
    id: "inv6",
    invoiceNumber: "INV-2025-0046",
    farmerId: "f2",
    farmerName: "Green Ridge Organics",
    storeId: "s3",
    storeName: "NatureMart",
    amount: 9300,
    issueDate: "2026-03-22",
    dueDate: "2026-05-21",
    status: "submitted",
    goods: "Certified Organic Spinach (1,100 lbs)",
    yieldRate: 8.0,
    platformFee: 279,
    fundedPercent: 0,
    totalInvestors: 0,
  },
  {
    id: "inv7",
    invoiceNumber: "INV-2025-0037",
    farmerId: "f1",
    farmerName: "Sunrise Valley Farm",
    storeId: "s1",
    storeName: "Fresh Market Co.",
    amount: 11000,
    issueDate: "2026-01-15",
    dueDate: "2026-03-15",
    fundedDate: "2026-01-18",
    paidDate: "2026-03-15",
    status: "paid",
    goods: "Winter Kale (1,400 lbs)",
    yieldRate: 8.0,
    platformFee: 330,
    fundedPercent: 100,
    totalInvestors: 6,
  },
  {
    id: "inv8",
    invoiceNumber: "INV-2025-0038",
    farmerId: "f3",
    farmerName: "Blue Sky Produce",
    storeId: "s2",
    storeName: "Valley Grocers",
    amount: 7400,
    issueDate: "2026-01-20",
    dueDate: "2026-03-20",
    fundedDate: "2026-01-24",
    paidDate: "2026-03-20",
    status: "paid",
    goods: "Cabbage (2,800 lbs)",
    yieldRate: 8.0,
    platformFee: 222,
    fundedPercent: 100,
    totalInvestors: 4,
  },
];

// ─── Investments ─────────────────────────────────────────────────────────────

export const INVESTMENTS: Investment[] = [
  {
    id: "i1",
    investorId: "inv_user_1",
    invoiceId: "inv1",
    invoiceNumber: "INV-2025-0041",
    storeName: "Fresh Market Co.",
    amount: 2000,
    investedDate: "2026-03-05",
    maturityDate: "2026-04-30",
    yieldRate: 8.0,
    projectedReturn: 2021.37,
    status: "active",
  },
  {
    id: "i2",
    investorId: "inv_user_1",
    invoiceId: "inv2",
    invoiceNumber: "INV-2025-0042",
    storeName: "NatureMart",
    amount: 1500,
    investedDate: "2026-03-11",
    maturityDate: "2026-05-07",
    yieldRate: 8.0,
    projectedReturn: 1519.73,
    status: "active",
  },
  {
    id: "i3",
    investorId: "inv_user_1",
    invoiceId: "inv3",
    invoiceNumber: "INV-2025-0043",
    storeName: "Fresh Market Co.",
    amount: 500,
    investedDate: "2026-03-14",
    maturityDate: "2026-05-11",
    yieldRate: 8.0,
    projectedReturn: 506.58,
    status: "active",
  },
  {
    id: "i4",
    investorId: "inv_user_1",
    invoiceId: "inv7",
    invoiceNumber: "INV-2025-0037",
    storeName: "Fresh Market Co.",
    amount: 1000,
    investedDate: "2026-01-18",
    maturityDate: "2026-03-15",
    yieldRate: 8.0,
    projectedReturn: 1013.15,
    actualReturn: 1013.15,
    status: "matured",
  },
  {
    id: "i5",
    investorId: "inv_user_1",
    invoiceId: "inv8",
    invoiceNumber: "INV-2025-0038",
    storeName: "Valley Grocers",
    amount: 750,
    investedDate: "2026-01-24",
    maturityDate: "2026-03-20",
    yieldRate: 8.0,
    projectedReturn: 759.45,
    actualReturn: 759.45,
    status: "matured",
  },
];

// ─── Investor profile (demo user) ────────────────────────────────────────────

export const DEMO_INVESTOR: Investor = {
  id: "inv_user_1",
  name: "Alex Rivera",
  balance: 7250.0,
  totalInvested: 5750,
  totalEarned: 52.88,
  activeInvestments: 3,
};

// ─── Platform stats ──────────────────────────────────────────────────────────

export const PLATFORM_STATS: PlatformStats = {
  totalInvoiceVolume: 297000,
  activeDeals: 6,
  capitalDeployed: 214800,
  totalFeesCollected: 8430,
  totalInvestors: 94,
  totalFarmers: 12,
  avgYieldRate: 8.1,
};

// ─── Chart data ──────────────────────────────────────────────────────────────

export const MONTHLY_VOLUME = [
  { month: "Oct", volume: 18400 },
  { month: "Nov", volume: 22100 },
  { month: "Dec", volume: 19800 },
  { month: "Jan", volume: 31200 },
  { month: "Feb", volume: 27600 },
  { month: "Mar", volume: 34800 },
];

export const INVESTOR_GROWTH_DATA = [
  { month: "Oct", earnings: 0 },
  { month: "Nov", earnings: 4.2 },
  { month: "Dec", earnings: 11.8 },
  { month: "Jan", earnings: 22.4 },
  { month: "Feb", earnings: 38.6 },
  { month: "Mar", earnings: 52.88 },
];
